service: healthcheck

package:
  patterns:
    - '!**'
    - 'node_modules/node-fetch/**'
    - 'node_modules/whatwg-url/**'
    - 'node_modules/webidl-conversions/**'
    - 'node_modules/tr46/**'
    - 'target/main.js'      

provider:
  name: aws
  runtime: nodejs16.x  
  region: eu-north-1
  environment:
    HEALTHCHECK_URLS: 'https://www.google.com,https://www.github.com'
    DELIVERY_METHOD: sms # email | sms
    EMAIL_RECIPIENT: name@example.com
    EMAIL_SENDER: name@example.com
    SMS_PHONE_NUMBER: '+358123123123'
    SMS_SENDER_ID: Oops # max 11 alphanumeric characters
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
           - sns:Publish # SMS
          Resource: "*"
        - Effect: "Allow"
          Action:
           - ses:sendEmail
          Resource: "*"

functions:
  check-health:
    handler: target/main.check
    events:
      - schedule: rate(1 hour)
